version: '3.3'

services:

  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
    networks:
      - net

    detectem:
    build:
      context: ./detectem
    command: python run.py
    depends_on:
      - splash
    ports:
      - 8080:8080
    networks:
      - net


networks:
  net:
    driver: bridge
