version: '3.3'

services:

  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
    networks:
      - net

  detectem:
    build:
      context: ./detectem
    command: python run.py
    environment:
      - SETUP_SPLASH=False
      - SPLASH_URL=http://splash:8050
    depends_on:
      - splash
    ports:
      - 5723:5723
    networks:
      - net


networks:
  net:
    driver: bridge
