version: '3.3'


# Docker compose services

services:

  # Service for rendering Javascript in a Splash browser

  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
    networks:
      - net

  # Service for detecting website software and technologies

  detectem:
    build:
      context: ./detectem
    command: python run.py
    environment:
      - SETUP_SPLASH=False
      - SPLASH_URL=http://splash:8050
    depends_on:
      - splash
    ports:
      - 8080:8080
    networks:
      - net

  # Crawling service

  scrapy:
    build:
      context: ./scrapy
    command: scrapy crawl detectem -a start_urls='["http://quotes.toscrape.com/"]'
    environment:
      - DETECTEM_URL=http://detectem:8080/detect
    depends_on:
      - detectem
    networks:
      - net


# Docker compose networks

networks:
  net:
    driver: bridge
